### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by Lammiwinks** [crazy-max/docker-unbound#26]
Hi` Crazy-Max! Thanks for pushing the redis support. My image updated today but I’m getting the following error:

Error loading shared library libhiredis.so. 1.0.0: No such file or directory (needed by /us/sbin/unbound-checkconf)’
Error relocating /us/sbin/unbound -checkconf freeReolvobiect: symbol not found
Error relocating us sin unbound-checkcont: redisconnectwithtimeout: symbol not found
Error relocating /us/sbin/unbound-checkconf redisFree: svmbol not found
redisCommand: symbol not found

Do you know what might be missing? Do I need to map a new volume in compose?

**Comment by crazy-max** [comment]
#27 should fix this issue.

**Comment by Lammiwinks** [comment]
Thank you :). All working now ❤️
